Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,22 +47,21 @@ jobs:
 
       - name: Trigger and monitor workflow (sh)
         run: |
-          INPUT_OWNER="Armen4343"
-          INPUT_REPO="repoB"
-          INPUT_EVENT_TYPE="trigger-exit"
-          INPUT_CLIENT_PAYLOAD="{}"
-          INPUT_TOKEN="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"
-          INPUT_MAX_TIME="1800"
-          INPUT_WAIT_TIME="10"
+          INPUT_OWNER="${{ inputs.owner }}"
+          INPUT_REPO="${{ inputs.repo }}"
+          INPUT_EVENT_TYPE="${{ inputs.event_type }}"
+          INPUT_CLIENT_PAYLOAD="${{ inputs.client_payload }}"
+          INPUT_TOKEN="${{ inputs.token }}"
+          INPUT_MAX_TIME="${{ inputs.max_time }}"
+          INPUT_WAIT_TIME="${{ inputs.wait_time }}"
 
           # Trigger the workflow
           echo "Triggering ${INPUT_EVENT_TYPE} in ${INPUT_OWNER}/${INPUT_REPO}"
-          resp=$(curl -L -X POST \
-            -H "Accept: application/vnd.github+json" \
+          resp=$(curl -X POST -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/dispatches" \
+            -H "Accept: application/vnd.github.v3+json" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer ${INPUT_TOKEN}" \
-            https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/dispatches \
-            -d '{"event_type": "${INPUT_EVENT_TYPE}", "client_payload": ${INPUT_CLIENT_PAYLOAD}}')
+            -d "{\"event_type\": \"${INPUT_EVENT_TYPE}\", \"client_payload\": ${INPUT_CLIENT_PAYLOAD} }")
 
           if [ -z "$resp" ]; then
             sleep 2
@@ -74,39 +73,45 @@ jobs:
 
           # Find the triggered workflow run
           counter=0
-          start_time=$(date +%s)
           while true; do
-            current_time=$(date +%s)
-            elapsed_time=$((current_time - start_time))
-
-            if [ "$elapsed_time" -ge "$INPUT_MAX_TIME" ]; then
-              echo "Time limit exceeded"
-              exit 1
-            fi
-
+            counter=$((counter + 1))
             workflow=$(curl -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/actions/runs?event=repository_dispatch" \
               -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: ${INPUT_TOKEN}" | jq '.workflow_runs[0]')
-            
-            wfid=$(echo "$workflow" | jq -r '.id')
-            conclusion=$(echo "$workflow" | jq -r '.conclusion')
+              -H "Authorization: Bearer ${INPUT_TOKEN}" | jq '.workflow_runs[0]')
 
-            if [ "$conclusion" != "null" ]; then
+            wtime=$(echo "$workflow" | jq -r '.created_at' | cut -c13-20)
+            atime=$(date -u +%T)
+            tdif=$(( $(date -d "$atime" +"%s") - $(date -d "$wtime" +"%s") ))
+
+            if [ "$tdif" -gt 10 ]; then
+              if [ "$counter" -gt 3 ]; then
+                echo "Workflow not found"
+                exit 1
+              else
+                sleep 2
+              fi
+            else
               break
             fi
-
-            sleep "$INPUT_WAIT_TIME"
           done
+
+          wfid=$(echo "$workflow" | jq -r '.id')
+          conclusion=$(echo "$workflow" | jq -r '.conclusion')
 
           echo "Workflow id is ${wfid}"
 
           # Wait for the workflow to complete
+          counter=0
           while [ "$conclusion" = "null" ]; do
-            conclusion=$(curl -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/actions/runs/${wfid}" \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: ${INPUT_TOKEN}" | jq -r '.conclusion')
-
+            if [ "$counter" -ge "$INPUT_MAX_TIME" ]; then
+              echo "Time limit exceeded"
+              exit 1
+            fi
             sleep "$INPUT_WAIT_TIME"
+            conclusion=$(curl -s "https://api.github.com/repos/${INPUT_OWNER}/${INPUT_REPO}/actions/runs/${wfid}" \
+            	-H "Accept: application/vnd.github.v3+json" \
+            	-H "Authorization: Bearer ${INPUT_TOKEN}" | jq -r '.conclusion')
+            counter=$((counter + INPUT_WAIT_TIME))
           done
 
           if [ "$conclusion" = "success" ]; then
